import Head from 'next/head'
import Image from 'next/image'
import Home from '../components/Home'
export default function Index() {
  return (
    <div className='flex flex-col items-center justify-center'>
      <Head>
        <title>Jamia Imam Ibn Taimiya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Home/>
      
    </div>
  )
}
